name-template: "@moyarich/workspace-tools v$RESOLVED_VERSION"
tag-template: "packages/workspace-tools@$RESOLVED_VERSION"
tag-prefix: "packages/workspace-tools@"

include-paths:
  - "packages/workspace-tools/**"

categories:
  - title: "Features"
    labels:
      - enhancement
      - feature

  - title: "Bug fixes"
    labels:
      - bug
      - fix

  - title: "Documentation"
    labels:
      - documentation
      - docs

  - title: "Dependencies"
    labels:
      - dependencies

  - title: "Maintenance"
    labels:
      - chore
      - maintenance
      - ci

exclude-labels:
  - skip-changelog

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"

version-resolver:
  major:
    labels:
      - breaking
  minor:
    labels:
      - enhancement
      - feature
  patch:
    labels:
      - bug
      - fix
      - dependencies
      - documentation
      - docs
      - chore
      - maintenance
      - ci
  default: patch

template: |
  ## What's Changed

  $CHANGES
