name: "Package Tests"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-packages:
    name: "Test packages"
    uses: ./.github/workflows/reusable_package-tests.yml
    with:
      packages-directory: packages
