name: Discover packages
on:
  workflow_call:
    inputs:
      packages-directory:
        required: false
        default: packages
        type: string
      include-private:
        required: false
        default: false
        type: boolean
      require-publish-config:
        required: false
        default: false
        type: boolean
      require-test-script:
        required: false
        default: false
        type: boolean
      require-build-script:
        required: false
        default: false
        type: boolean
      node-version:
        required: false
        default: "24"
        type: string
      exclude-package-names:
        required: false
        default: '[]'
        type: string
    outputs:
      packages:
        value: ${{ jobs.discover.outputs.packages }}
      matrix:
        value: ${{ jobs.discover.outputs.matrix }}
      has-packages:
        value: ${{ jobs.discover.outputs.has-packages }}
      count:
        value: ${{ jobs.discover.outputs.count }}
permissions: {}
jobs:
  discover:
    permissions:
      contents: read
    uses: moyarich/reusable-workflows/.github/workflows/reusable_discover-packages.yml@main
    with:
      packages-directory: ${{ inputs.packages-directory }}
      include-private: ${{ inputs.include-private }}
      require-publish-config: ${{ inputs.require-publish-config }}
      require-test-script: ${{ inputs.require-test-script }}
      require-build-script: ${{ inputs.require-build-script }}
      node-version: ${{ inputs.node-version }}
      exclude-package-names: ${{ inputs.exclude-package-names }}
