name: Set issue dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/set-issue-dependencies.yml"

permissions:
  contents: read
  issues: write

jobs:
  issue-2:
    name: Set #2 blocked by #3
    uses: moyarich/reusable-workflows/.github/workflows/reusable_manage-issue-dependencies.yml@v0
    with:
      issue: "2"
      related_issues: "3"
      relationship: blocked-by
      action: add

  issue-9:
    name: Set #9 blocked by #7
    uses: moyarich/reusable-workflows/.github/workflows/reusable_manage-issue-dependencies.yml@v0
    with:
      issue: "9"
      related_issues: "7"
      relationship: blocked-by
      action: add
